apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: t0ouwqwvn-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/t0ouwqwvn-java-quarkus